---
# tasks file for fluentd

- name: Load a variable file based on the OS type, or a default if not found.
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "default.yml"
      paths:
        - 'vars'

- name: Install required packages
  become: true
  package:
    state: present
    name: "{{ item }}"
  with_items: "{{ packages }}"
  register: task_result
  until: task_result is success
  retries: 5

- name: Create required directories
  become: true
  file:
    path: "{{ item.dest }}"
    state: directory
    recurse: yes
    owner: root
    group: root
    mode: "{{ item.mode | default(omit) }}"
  loop:
    - {dest: "/etc/fluentd"}

- name: Write Fluentd config files
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0660
  loop:
    - {src: "env.j2", dest: "/etc/fluentd/env"}
    - {src: "fluentd.conf.j2", dest: "/etc/fluentd/fluentd.conf"}
  notify:
    - restart fluentd

- name: Write Fluentd Systemd unit file
  become: true
  template:
    src: "fluentd.service.j2"
    dest: "{{ fluentd_systemd_unit_path }}"
  notify:
    - restart fluentd

