---
# tasks file for fluentd

- name: Load a variable file based on the OS type, or a default if not found.
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "default.yml"
      paths:
        - 'vars'

- name: Install required packages
  become: true
  package:
    state: present
    name: "{{ item }}"
  with_items: "{{ packages }}"
  register: task_result
  until: task_result is success
  retries: 5

- name: Create Fluentd group
  become: true
  group:
    name: "{{ fluentd_os_user }}"
    state: present

- name: Create Fluentd user
  become: true
  user:
    name: "{{ fluentd_os_user }}"
    group: "{{ fluentd_os_group }}"

- name: Create required directories
  become: true
  file:
    path: "{{ item.dest }}"
    state: directory
    recurse: yes
    owner: "{{ fluentd_os_user }}"
    group: "{{ fluentd_os_group }}"
    mode: "{{ item.mode | default(omit) }}"
  loop:
    - {dest: "/etc/fluentd"}

- name: Copy systemd.conf tmpfiles to /etc to override journal permission settings
  become: true
  copy:
    src: /lib/tmpfiles.d/systemd.conf
    dest: /etc/tmpfiles.d/systemd.conf
    owner: root
    group: root
    mode: 0644

- name: Change permisson on journal files to give read permissions
  become: true
  lineinfile:
    path: /etc/tmpfiles.d/systemd.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - {regexp: '^z /var/log/journal/%m/system.journal', line: 'z /var/log/journal/%m/system.journal 0644 root systemd-journal - -' }
    - {regexp: '^z /var/log/journal/%m/\*.journal\*', line: 'z /var/log/journal/%m/*.journal* 0644 root systemd-journal - -' }

- name: Reread tmpfiles configs an create all files with proper permissiong
  become: true
  command: /usr/bin/systemd-tmpfiles --create

- name: Write Fluentd config files
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ fluentd_os_user }}"
    group: "{{ fluentd_os_group }}"
    mode: 0660
  loop:
    - {src: "env.j2", dest: "/etc/fluentd/env"}
    - {src: "fluentd.conf.j2", dest: "/etc/fluentd/fluentd.conf"}
  notify:
    - restart fluentd

- name: Write Fluentd Systemd unit file
  become: true
  template:
    src: "fluentd.service.j2"
    dest: "{{ fluentd_systemd_unit_path }}"
  notify:
    - restart fluentd

